version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # Add healthcheck for robust deployment
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/resources"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # For development purposes
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules # Don't override node_modules
    restart: unless-stopped